regiones = {
     'I' : 'Región de Tarapacá',
     'II' : 'Región de Antofagasta',
     'III' : 'Región de Atacama',
     'IV' : 'Región de Coquimbo',
     'V' : 'Región de Valparaíso',
     'VI' : 'Región del Libertador General Bernardo O’Higgins',
     'VII' : 'Región del Maule',
     'VIII' : 'Región del Biobío',
     'IX' : 'Región de La Araucanía',
     'X' : 'Región de Los Lagos',
     'XI' : 'Región Aysén del General Carlos Ibáñez del Campo',
     'XII' : 'Región de Magallanes y Antártica Chilena',
     'M' : 'Región Metropolitana de Santiago',
     'XIV' : 'Región de Los Ríos',
     'XV' : 'Región de Arica y Parinacota',
     'XVI' : 'Región de Ñuble',
}
