# Generated by Django 2.1.7 on 2019-03-21 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocatas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('evaluacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tocata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tocatas.Tocata')),
            ],
        ),
    ]
